query Asset($id: ID!) {
  asset(where: { id: $id }) {
    id
    handle
    fileName
    original: url(
      transformation: {
        image: { compress: { metadata: true } }
        document: { output: { format: autoImage } }
      }
    )
    hero: url(
      transformation: {
        image: {
          resize: { width: 1280 }
          compress: { metadata: true }
          quality: { value: 100 }
        }
        document: { output: { format: autoImage } }
      }
    )
    publishedAt
    height
    width
    mimeType
    size
    alt
    createdBy {
      name
      picture
    }
  }
}
